
version: 2

sources:
  - name: MTS_RAW
    database: BOOTCAMP
    schema: MTS_RAW
    tables:
      - name: MTS_SALES_DATA
        columns:
          - name: "Rep Name"
            tests:
              - not_null
          - name: "Rep Number"
            tests:
              - not_null
              - unique

  - name: MTS
    database: BOOTCAMP
    schema: ETL
    tables:
      - name: T_PROCESS_AUDIT_LOG